#!/bin/sh

mkdir -p "/Users/pengweiqi/Library/Application Support/Sublime Text 3/Installed Packages"
cp "/Users/pengweiqi/Downloads/Package Control.sublime-package" \
   "/Users/pengweiqi/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"

mkdir -p "/Users/pengweiqi/Library/Application Support/Sublime Text 3/Packages/User"
cp "/Users/pengweiqi/Desktop/projects/Sublime-Life/Package Control.sublime-settings.template" \
   "/Users/pengweiqi/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings"
